"""add_extended_farm_fields

Revision ID: 1602a5f4861a
Revises: 437549604295
Create Date: 2025-05-12 14:09:31.848944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1602a5f4861a'
down_revision = '437549604295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('soil_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ph_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('soil_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('irrigation_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('water_source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_column('water_source')
        batch_op.drop_column('irrigation_type')
        batch_op.drop_column('soil_notes')
        batch_op.drop_column('ph_level')
        batch_op.drop_column('soil_type')
        batch_op.drop_column('region')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.drop_table('farm_team_members')
    # ### end Alembic commands ###
